var gamePattern = [];                                      //it is an array for storing the pattern provided randomly by computer
var buttonColours = ["red", "green", "blue", "yellow"];    //this stores types of buttons
var randomchosencolour;                                    //this is a variable for storing the random colour generated by computer
var userClickedPattern = [];                               //it is an array for storing the pattern entered by user
var Level = 0;                                             //it is for keeping a count on level        
var started = false;                                       

$(document).keypress(function(){                           //this checks whether a key is pressed on the keyboard
    if(!started){
      $("h1").text("Level " + Level);
      nextSequence(); 
      started=true;
    }
});

$(".btn").click(function(){                                //this checks if one of the buttons are clicked. then, execute the event handler
    var userChosenColour =  $(this).attr("id");            //storing the value of what colour does the user choose to the variable 
    userClickedPattern.push(userChosenColour);
    playSound(userChosenColour);
    animatePress(userChosenColour);
    checkAnswer(userClickedPattern.length-1);
})

function checkAnswer(currentLevel) {
    if(gamePattern[currentLevel]===userClickedPattern[currentLevel]){
        if(gamePattern.length===userClickedPattern.length){
            setTimeout(function(){
                nextSequence();
            },1000);
        }
    }
    else{
        var wrong = "wrong";
        playSound(wrong);
        $("body").addClass("game-over");
        setTimeout(function () {                           //this is used to add a delay
            $("body").removeClass("game-over");
          }, 200); 
          $("h1").text("Game Over, Press Any Key to Restart"); 
          startOver();
   }
}

function nextSequence() {
    userClickedPattern = [];
    Level++;
    $("h1").text("Level " + Level);
    var randomNumber = Math.floor(Math.random()*4);
    randomchosencolour = buttonColours[randomNumber];
    gamePattern.push(randomchosencolour);
    $("#"+randomchosencolour).fadeIn(100).fadeOut(100).fadeIn(100);
    playSound(randomchosencolour);
}

function playSound(name) {
    var audio = new Audio("sounds/" + name + ".mp3");
    audio.play();
}

function animatePress(currentColour){
    $("#" + currentColour).addClass("pressed");
    setTimeout(function () {
        $("#" + currentColour).removeClass("pressed");
      }, 100);
}

function startOver() {
    Level=0;
    gamePattern=[];
    started=false;
}